#Time intervals are in hh:mm:ss format

[DEFAULT]
FL_CUTOFF = M1.0
NF_CUTOFF			= B9.9
NF_CLEAR_FORWARD	= 24:00:00
NF_CLEAR_BACKWARD	= 24:00:00
OBSERVATION_WINDOW	= 24:00:00
PREDICTION_WINDOW	= 24:00:00
CADENCE				= 00:12:00
TASK = EPS_TAU
#TASK				= WITHIN
#[EPS_TAU]
EPSILON = 01:00:00
TAU			= %(CADENCE)s


[24_24]
FL_CUTOFF			= C9.9
NF_CUTOFF			= B9.9
NF_CLEAR_FORWARD	= 06:30:00
NF_CLEAR_BACKWARD	= 06:30:00
OBSERVATION_WINDOW	= 24:00:00
PREDICTION_WINDOW	= 24:00:00
CADENCE				= 00:12:00
TASK				= EPS_TAU
	[EPS_TAU]
	EPSILON			= 02:00:00
	EPSILON			= %(CADENCE)s

[12_12]
FL_CUTOFF			= C9.9
NF_CUTOFF			= B9.9
NF_CLEAR_FORWARD	= 06:30:00
NF_CLEAR_BACKWARD	= 06:30:00
OBSERVATION_WINDOW	= 12:00:00
PREDICTION_WINDOW	= 12:00:00
CADENCE				= 00:12:00